(ns directus-schema.links
  "Generates Directus presentation-links fields in schema/snapshot.json
   from :directus metadata on reitit route definitions.

   Called via: clj -X<alias> with a wrapper fn in the consuming project.
   Reads:  routes and domain from the caller via opts map
   Writes: snapshot-path (idempotent — replaces previously generated fields)"
  (:require [clojure.data.json :as json]
            [clojure.string :as str]
            [reitit.core :as r]))

(def ^:private generated-marker "Auto-generated by directus-schema.links")

;; ---------------------------------------------------------------------------
;; Path template conversion
;; ---------------------------------------------------------------------------

(defn- template->directus-path
  "Converts a reitit route template to a Directus presentation-link path.
   Replaces {param} with {{field}} via :params mapping, applies :static-params
   as literals, and substitutes the locale value for {locale-param}.
   Safe for all reitit param syntaxes — compiled templates are always normalized
   to {bracket} notation."
  [template {:keys [params static-params]} locale locale-param]
  (-> (reduce-kv (fn [p k v]
                   (str/replace p (str "{" (name k) "}") (str "{{" v "}}")))
                 template params)
      (as-> p (reduce-kv (fn [p k v]
                           (str/replace p (str "{" (name k) "}") v))
                         p (or static-params {})))
      (str/replace (str "{" locale-param "}") locale)))

;; ---------------------------------------------------------------------------
;; Snapshot field generation
;; ---------------------------------------------------------------------------

(defn- needs-bump?
  "Returns true if the collection has any field at sort position 1,
   meaning we need to bump to make room for the generated field."
  [fields collection]
  (some #(and (= collection (:collection %))
              (= 1 (get-in % [:meta :sort])))
        fields))

(defn- bump-sort-values
  "Increments sort values for fields in collections that have a sort=1 conflict.
   Only bumps collections that actually need it, ensuring idempotency."
  [fields collections]
  (let [bump-colls (set (filter #(needs-bump? fields %) collections))]
    (mapv (fn [field]
            (if (and (bump-colls (:collection field))
                     (get-in field [:meta :sort]))
              (update-in field [:meta :sort] inc)
              field))
          fields)))

(defn- make-presentation-link-field
  [collection path]
  {:collection collection
   :field      "website_link"
   :type       "alias"
   :meta       {:collection       collection
                :conditions       nil
                :display          nil
                :display_options  nil
                :field            "website_link"
                :group            nil
                :hidden           false
                :interface        "presentation-links"
                :note             generated-marker
                :options          {:links [{:label "View on Website"
                                           :icon  "open_in_new"
                                           :type  "normal"
                                           :url   path}]}
                :readonly         false
                :required         false
                :searchable       false
                :sort             1
                :special          ["alias" "no-data"]
                :translations     nil
                :validation       nil
                :validation_message nil
                :width            "full"}})

(defn- remove-generated-fields [fields]
  (vec (remove #(= generated-marker (get-in % [:meta :note])) fields)))

;; ---------------------------------------------------------------------------
;; Main entry point
;; ---------------------------------------------------------------------------

(defn generate-links
  "Generates Directus presentation-links from reitit route metadata, patches snapshot.

   Required opts:
     :routes        - reitit route tree (caller responsible for any locale prefix wrapping)
     :domain        - canonical domain string, no scheme (e.g. \"example.com\")

   Optional opts:
     :snapshot-path - path to JSON snapshot (default \"schema/snapshot.json\")
     :locale        - locale string substituted for {locale-param} in paths (default \"de\")
     :locale-param  - route param name used as locale placeholder (default \"locale\")"
  [{:keys [routes domain snapshot-path locale locale-param]
    :or   {snapshot-path "schema/snapshot.json"
           locale        "de"
           locale-param  "locale"}}]
  (let [router  (r/router routes)
        routes  (->> (r/compiled-routes router)
                     (filter (fn [[_ data _]] (:directus data))))

        snapshot     (json/read-str (slurp snapshot-path) :key-fn keyword)
        clean-fields (remove-generated-fields (:fields snapshot))

        new-fields (mapv (fn [[template data _]]
                           (let [path (template->directus-path
                                       template (:directus data) locale locale-param)
                                 url  (str "https://" domain path)]
                             (make-presentation-link-field
                              (get-in data [:directus :collection]) url)))
                         routes)

        collections  (mapv (comp :collection :directus second) routes)
        bumped-fields (bump-sort-values clean-fields collections)
        updated       (assoc snapshot :fields (into bumped-fields new-fields))]

    (spit snapshot-path (json/write-str updated :escape-slash false))

    (println "[directus-schema.links] Generated" (count new-fields) "presentation-links:")
    (doseq [f new-fields]
      (println " " (:collection f) "→" (get-in f [:meta :options :links 0 :url])))))
